### ISSUE TITLE
QAOA Maxcut currently failing on the latest version of PennyLane and autograd

### ISSUE THREAD

**Issue by josh146** [XanaduAI/qml#36]
The QAOA maxcut tutorial is currently failing with the following traceback:

```
  File "implementations/tutorial_qaoa_maxcut.py", line 208, in circuit
    U_C(gammas[i])
IndexError: index 1 is out of bounds for axis 0 with size 1
```

The issue seems to be passing the parameter `gamma`. At line 246,
```python
neg_obj -= 0.5 * (1 - circuit(gammas, betas, edge=edge, n_layers=n_layers))
```
it can be seen that `gamma = Autograd ArrayBox with value [0.00617866 0.00415137]`. However, within the QNode at line 202,
```python
@qml.qnode(dev)
def circuit(gammas, betas, edge=None, n_layers=1):
    # apply Hadamards to get the n qubit |+> state
    [print(2, i.val) for i in gammas if isinstance(i, qml.variable.Variable)]
```
we have `gamma = [0.006178660018330691]` - the second element is 'missing'.

**Comment by antalszava** [comment]
The problem seems to be related to the fact that there is only one `QNode` that is being created throughout the entire execution of the script.

When calling `_construct` with two parameters for gamma, the same `self.arg_vars` will be used as created for only one parameter (as it is `not None`), yielding the error.

A quick way to check this would be commenting out lines ``bitstrings1 = qaoa_maxcut(number_of_layers=1)[1]`` and ``plt.hist(bitstrings1, bins=bins)``.

Going forward with trying to figure out why there's only one `QNode` that is being created.

**Comment by antalszava** [comment]
With one `QNode` the logic should be altered here such that there is a more in-depth check comparing the current `self.arg_vars` and the new `Variables`: https://github.com/XanaduAI/pennylane/blob/719e27c7d046e7d488b8c68685fe803f4f5afa9f/pennylane/qnodes/base.py#L500

**Comment by josh146** [comment]
Thanks @antalszava! Was this bug introduced with the circuit drawer then? We should add a test to PL to test this specific edge case, and make sure it is fixed.

**Comment by antalszava** [comment]
With https://github.com/XanaduAI/pennylane/pull/505 merged, I'll close this for now.
